version: '3.4'

services:
  currency-exchange:
    image: filipbojovic/mmv2-currency-exchange-service:latest
    mem_limit: 700m # 700mb of memory for this container
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
      # - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin-server:9411/api/v2/spans
      # RABBIT_URI: amqp://guest:guest@rabbitmq:5672/%2F
      # SPRING_RABBITMQ_HOST: rabbitmq
      # SPRING_ZIPKIN_SENDER_TYPE: rabbit

  currency-conversion:
    image: filipbojovic/mmv2-currency-conversion-service:latest
    mem_limit: 700m # 700mb of memory for this container
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      # - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin-server:9411/api/v2/spans
      # RABBIT_URI: amqp://guest:guest@rabbitmq:5672/%2F
      # SPRING_RABBITMQ_HOST: rabbitmq
      # SPRING_ZIPKIN_SENDER_TYPE: rabbit
    
  api-gateway:
    image: filipbojovic/mmv2-api-gateway:latest
    mem_limit: 700m # 700mb of memory for this container
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      # - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT:  http://zipkin-server:9411/api/v2/spans
      # RABBIT_URI: amqp://guest:guest@rabbitmq:5672/%2F
      # SPRING_RABBITMQ_HOST: rabbitmq
      # SPRING_ZIPKIN_SENDER_TYPE: rabbit
    
  naming-server:
    image: filipbojovic/mmv2-naming-server:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin
    mem_limit: 700m
    ports:
      - "9411:9411"
    # depends_on:
    #   - rabbitmq
    networks:
      - currency-network
    # environment:
    #   RABBIT_URI: amqp://guest:guest@rabbitmq:5672/%2F

  # rabbitmq:
  #   image: rabbitmq:3.7.8-management  
  #   expose:
  #     - "5672"
  #     - "15672"
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   networks:
  #     - currency-network

networks:
  currency-network: